name: .NET

on:
  push:
    branches: [ main ]

env:
  WORKING_DIRECTORY: TranslaGenixAPI

jobs:
  ci:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.WORKING_DIRECTORY}}
    - name: Build
      run: dotnet build --no-restore ${{env.WORKING_DIRECTORY}}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{env.WORKING_DIRECTORY}}
